CREATE TABLE IF NOT EXISTS config_sistema (
  clave VARCHAR(64) NOT NULL,
  valor TEXT,
  updated_by VARCHAR(255) DEFAULT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (clave)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
